spring:
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://localhost:3306/xyz
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true